### ISSUE TITLE
Data Transfer Tools for upload/download

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-management#10]
Implement Data Transfer Tool to upload/download data from SONG/SCORE

## Background
- some tools already exist 
- inventory current tool
- decide if we want to implement these tools in this manner, or develop a new data transfer tool
- The workflows generate some QC files that are dumped in S3, not song/score.  We don't want these in song/score, but we do want them searchable. 

## Exit Criteria 
- [x] tarball extractor in Nextflow
- [x]  song upload tool in Nextflow 
- [x]  song download tool in Nextflow

**Comment by lepsalex** [comment]
WIP: https://github.com/icgc-argo/nextflow-data-processing-utility-tools/

Needs testing but for that we need the docker container with the updated SONG/SCORE clients that support everything in the above.

Closing for now because it should only require very minor adjustments once ready. 🤞
