### ISSUE TITLE
E2E runningof DNA-seq workflow 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-management#11]
The main workflow uses several tools [ main wf, subworkflows, and data transfer wfs]

These need to be tied together into a pipeline that calls all of these steps in a single flow. 

- dna-seq running start to finish 
- includes all subworkflows 

@rosibaj  move ticket to https://github.com/icgc-argo/nextflow-dna-seq-processing-wfs after sprint

**Comment by lepsalex** [comment]
Working end-to-end both locally and in Kubernetes (https://github.com/icgc-argo/nextflow-dna-seq-alignment)
