### ISSUE TITLE
Spec for Workflow Authorization 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-management#15]
- Figure out to not expose the API-Key in the params
- Retrieve the Ego-user-id into the params to identify the user in workflow runs 
- look at tenancy

**Comment by lepsalex** [comment]
@rosibaj https://wiki.oicr.on.ca/display/icgcargotech/Workflow+Authorization - moving to review, @andricDu and I discussed already, happy to get your input as well.
