### ISSUE TITLE
🐛 Resume runs through ModelTee receive different workDir in RDPC Prod

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-management#209]
## Describe the bug
Using ModelTee to resume a failed job with sessionId: 148bef4b-0b04-43ad-ae3b-57e523b00dee (runId: wes-8d446b69ad5d4ad78014675572e39adc) in RDPC Prod
The job had the following engine params:
```
{
	"launchDir": "/nfs-2-c4/launch",
	"projectDir": "/nfs-2-c4/projects/rna-seq-alignment/0.2.0/icgc-argo-workflows/rna-seq-alignment",
	"resume": "false",
	"revision": "0.2.0",
	"workDir": "/nfs-2-c4/work"
}
```

The resumed job with runId: wes-b6d55fc19b564129a8030e2b852b6ba5
got kicked off while failed with errors:
`Error Msg: Nextflow pod failed to start: N E X T F L O W ~ version 21.04.3 Launching `icgc-argo-workflows/rna-seq-alignment` [wes-b6d55fc19b564129a8030e2b852b6ba5] - revision: 82ebc92296 [0.2.0] Can't find a run with the specified id: 148bef4b-0b04-43ad-ae3b-57e523b00dee -- Execution can't be resumed`

Looking into the auto-filled engine params:
```
{
	"launchDir": "file:///nfs-2-c3/launch",
	"projectDir": "file:///nfs-2-c3/projects/rna-seq-alignment/0.2.0",
	"resume": "false",
	"revision": "0.2.0",
	"workDir": "file:///nfs-2-c3/work"
}
```
The reason the job failed is that 
1. the resumed job was launched with workDir `nfs-2-c3` not from `nfs-2-c4`. 
2. nextflow can't find the run history so as to resume the job.

## Expected behaviour
- resumed job kicked off through Model Tee should be launched with the same workDir as the failed job.

**Comment by UmmulkiramR** [comment]
When ModelTee fires fires a job it sends the <SCHEDULE_DIR> template in the request. When it fires a 'resume' job request it does the same. During both times it is scheduler's responsibility to replace the <SCHEDULE_DIR> template with the actual work directory values. 

Now, when a job is resumed, the scheduler knows nothing about the last run and the work dirs used at the time the job first failed and when there are multiple jobs running at the same time there is no guarantee the scheduler will assign the same directories for the resumed jobs. 

To solve this, the Model Tee code has been modified to send actual directory values in the requests when resuming jobs.

**Comment by Buwujiu** [comment]
Task completed
