### ISSUE TITLE
🐛 Workflow Management's consumer connection with RabbitMQ keeps breaking on Prod.

### ISSUE THREAD

**Issue by UmmulkiramR** [icgc-argo/workflow-management#210]
Workflow Management's consumer connection with RabbitMQ keeps breaking on Prod due to which workflow jobs get stuck in Queued state. This has happened more frequently in the last few days. Need to investigate.

**Comment by Buwujiu** [comment]
PR made, needs configuration changes, don't know why connection issue happened. No more work needed, just need to monitor, for now it's working as expected, will close now.
