### ISSUE TITLE
Merge search and gateway swagger

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-management#26]
We want one way to interact with the API. Currently we have 2 swaggers for search and management microservice. 

We would like a single API point to interact with for the workflow systems,

## Expected Behavior
- [ ] There should be a single swagger with all workflow endpoints listed 
- [ ] These endpoints are functional and can be tested with little to no input from a developer

**Comment by rosibaj** [comment]
@lepsalex  or @Buwujiu what is the swagger link for the new merged swagger?

**Comment by Buwujiu** [comment]
@rosibaj it's not deployed yet, we do have a new repo for it, workflow-docs!

**Comment by rosibaj** [comment]
hmm @Buwujiu im not sure this should be closed yet then!  Is there a blocker to deploying it?

**Comment by Buwujiu** [comment]
@rosibaj I will create tickets for deployment, I thought this was an investigation ticket.
