### ISSUE TITLE
Workflow Start Error Handling 

### ISSUE THREAD

**Issue by lepsalex** [icgc-argo/workflow-management#27]
Certain error classes are not being caught by the runs start endpoint and resulting in a 200 response and in some cases even an incomplete workflow event.

**Known scenarios:**
* Starting a WF that has it's git in an "incompatible state" (branch does not exist, no main.nf file, etc), resulting in `Remote resource not found: https://api.github.com/repos/icgc-argo/dna-seq-processing-wfs/contents/main.nf`
* Using java/groovy classes in your workflow resulting in a `WARN: Process 'ProcessName' cannot be executed by 'k8s' executor -- Using 'local' executor instead`
* File reference errors, such as `No such file: /mnt/volume/nextflow/reference/tiny-grch38-chr11-530001-537000.fai`

There are many groovy errors that are being sent from nextflow, but they are not always clear. 

- Define General Error Handling method to capture the error types 
- Nextflow has some parent error classes that are extended to specific errors 
- Investigate the different stopping errors that are being recorded
- Workflows fail silently in 2 ways: 1) can be stuck as "running" when they are really stalled 2)
(Examples: `file not found`, `groovy not installed`) but the actual error is not reported

**Comment by rosibaj** [comment]
Open a ticket with nextflow bc the order of operations in their gitflow is faulty
- clone repo
- do all checks before checking out the branch 
failed to execute bc it did not switch to the branch

**Comment by rosibaj** [comment]
moving forward until PR is wrapped up - additional tickets have been made
