### ISSUE TITLE
Cancel Endpoint is not working 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-management#50]

**Comment by Buwujiu** [comment]
issue happens  in rdpc cluster, when canceling a running workflow, the follow error is returned: 
```
  "msg": "Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [rdpc-collab]  failed.",
```
This is due to permission issue in rdpc cluster, working with @henro001 to address this.

**Comment by Buwujiu** [comment]
Issue is fixed by @henro001 , verified that cancel endpoint is working in rdpc prod.

**Comment by akachru-github** [comment]
This is still occurring in DEV and QA. Reopening.

**Comment by Buwujiu** [comment]
Tested in rdpc dev and qa, cancel is working as expected, closing ticket.
