### ISSUE TITLE
Feature Request: Creating K8s secrets for workflows 

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/workflow-management#98]
Workflow secrets are passed in `params` which are indexed and visible. 

We want workflow management to create K8s secrets for use in sharing auth creds with tasks in a secure manner. 

## Detailed Description
When doing a `POST /runs` with a new workflow, we want workflow-management to create a new kubernetes secret that is usable/mountable/readable by tasks in the new workflow run.

Which type of secret should me managed via configuration and run profiles allowing for the selection of a secret provider.

Two secret providers are needed initially. 

1. API Key secret provider, where a system API Key is configured for all workflows to use.
2. Client Credentials provider, where the system is configured to generate App JWTs on demand at schedule time for a workflow.

## Possible Implementation
- Abstract class for SecretProvider
- Implementation of a api key provider
- Implementation of a app jwt provider
- associated config and run profiles
- tests where possible

**Comment by rosibaj** [comment]
@andricDu is there anything to deploy here?  Do we have some next steps for testing this?

**Comment by andricDu** [comment]
Following up from yesterday so we don't forget the discussion. The version containing this feature has been deployed to QA where it is working. When we deploy a new version of management to PROD we can close this issue. 

We should follow up this ticket and the nextflow song/score secrets ticket with a ticket scoped to rolling out workflows with the secrets provider enabled and set to API key.
